name: Build and Deploy Spring Boot App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradle
        run: chmod +x ./gradlew

      - name: Build to Boot Project
        run: ./gradlew BootJar -x test
      
      - name: Verify build jar
        run: |
          ls -la build/libs/
          if [ ! -f build/libs/*.jar ]; then
            echo "빌드 실패..ㅠㅠ"
            exit 1
          fi
          echo "빌드파일 만들기 성공!"

      - name: Change Maintenance Mode
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/project/backend
            cp /home/ubuntu/project/frontend/dist/index.html /home/ubuntu/project/maintenance/index_tmp.html
            cp /home/ubuntu/project/maintenance/index.html /home/ubuntu/project/frontend/dist/index.html
            docker nginx restart
            echo "유지보수 모드 활성화"
            sleep 5

      - name: Deploy Boot App To EC2
        if: github.event_name == 'push'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/ubuntu/project/backend"
          strip_components: 2

      - name: Restart Container
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/ubuntu/project
            docker restart api
            sleep 30
            cp /home/ubuntu/project/maintenance/index_tmp.html /home/ubuntu/project/frontend/dist/index.html





